-- Run this script as user DEMO_TRG --

CREATE SEQUENCE TRG_EMPLOYEE_SEQ 
  MINVALUE   1
  START WITH 1
/
 
CREATE TABLE TRG_SALGRADE
(
  GRADE  NUMBER,
  LOSAL  NUMBER,
  HISAL  NUMBER
)
/


CREATE TABLE TRG_DEPT
(
  DEPTNO  NUMBER(2),
  DNAME   VARCHAR2(14 BYTE),
  LOC     VARCHAR2(13 BYTE)
)
/


CREATE TABLE TRG_BONUS
(
  ENAME  VARCHAR2(10 BYTE),
  JOB    VARCHAR2(9 BYTE),
  SAL    NUMBER,
  COMM   NUMBER
)
/



CREATE TABLE TRG_EMP
(
  EMPNO     NUMBER(4),
  ENAME     VARCHAR2(10 BYTE),
  JOB       VARCHAR2(9 BYTE),
  MGR       NUMBER(4),
  HIREDATE  DATE,
  SAL       NUMBER(7,2),
  COMM      NUMBER(7,2),
  DEPTNO    NUMBER(2)
)
/

CREATE TABLE TRG_EMPLOYEE
(  
  EMP_ID    NUMBER(10),
  EMPNO     NUMBER(4),
  ENAME     VARCHAR2(10 BYTE),
  JOB       VARCHAR2(9 BYTE),
  MGR       NUMBER(4),
  HIREDATE  DATE,
  SAL       NUMBER(7,2),
  COMM      NUMBER(7,2),
  DEPTNO    NUMBER(2),
  DNAME     VARCHAR2(14),
  ACTIVE_FLAG  NUMBER(1),
  EFF_BEG_DT   DATE,
  EFF_END_DT   DATE
)
/


CREATE TABLE DATABASE_LIST
(
  SEQ           NUMBER,
  DATABASE_URL  VARCHAR2(1000 BYTE)
)
/


CREATE UNIQUE INDEX PK_TRG_DEPT ON TRG_DEPT
(DEPTNO)
/


CREATE UNIQUE INDEX PK_TRG_EMP ON TRG_EMP
(EMPNO)
/

CREATE UNIQUE INDEX PK_TRG_EMPLOYEE ON TRG_EMPLOYEE 
(EMP_ID)
/

CREATE         INDEX IN_TRG_EMPLOYEE ON TRG_EMPLOYEE 
(EMPNO)
/


CREATE UNIQUE INDEX PK_DATABASE_LIST ON DATABASE_LIST
(SEQ)
/



ALTER TABLE TRG_DEPT ADD (
  CONSTRAINT PK_TRG_DEPT
 PRIMARY KEY
 (DEPTNO))
/


ALTER TABLE TRG_EMP ADD (
  CONSTRAINT PK_TRG_EMP
 PRIMARY KEY
 (EMPNO))
/

ALTER TABLE TRG_EMPLOYEE ADD (
  CONSTRAINT PK_TRG_EMPLOYEE 
 PRIMARY KEY
 (EMP_ID))
/



ALTER TABLE DATABASE_LIST ADD (
  CONSTRAINT PK_DATABASE_LIST
 PRIMARY KEY
 (SEQ))
/

--------------

CREATE TABLE TRG_EMPDEPT
(
  EMPNO     NUMBER(4),
  ENAME     VARCHAR2(10 BYTE),
  JOB       VARCHAR2(9 BYTE),
  MGR       NUMBER(4),
  HIREDATE  DATE,
  SAL       NUMBER(7,2),
  COMM      NUMBER(7,2),
  DNAME     VARCHAR2(14 BYTE),
  LOC       VARCHAR2(13 BYTE)
)

---------------


CREATE TABLE TRG_WORK_HIST
(
  EMPNO        NUMBER(4)  NOT NULL,
  DATE_WORKED  NUMBER(8)  NOT NULL,
  HOURS        NUMBER(5,2)
)
PARTITION BY RANGE (DATE_WORKED) 
(  
  PARTITION P201301 VALUES LESS THAN (20130201)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201302 VALUES LESS THAN (20130301)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201303 VALUES LESS THAN (20130401)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201304 VALUES LESS THAN (20130501)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201305 VALUES LESS THAN (20130601)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201306 VALUES LESS THAN (20130701)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201307 VALUES LESS THAN (20130801)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201308 VALUES LESS THAN (20130901)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201309 VALUES LESS THAN (20131001)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201310 VALUES LESS THAN (20131101)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201311 VALUES LESS THAN (20131201)
    LOGGING
    NOCOMPRESS,  
  PARTITION P201312 VALUES LESS THAN (20140101)
    LOGGING
    NOCOMPRESS
)
PARALLEL ( DEGREE 4 INSTANCES DEFAULT );


CREATE UNIQUE INDEX TRG_WORK_HIST_PK ON TRG_WORK_HIST
(EMPNO, DATE_WORKED)
  LOCAL 
PARALLEL ( DEGREE 4 INSTANCES DEFAULT );


ALTER TABLE TRG_WORK_HIST ADD (
  CONSTRAINT TRG_WORK_HIST_PK
 PRIMARY KEY
 (EMPNO, DATE_WORKED));

--------------

